name: CI - Pipeline & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Run pipeline (sample data)
        run: |
          python tools/run_pipeline.py --src tests/data --out exports
      - name: Upload exports
        uses: actions/upload-artifact@v4
        with:
          name: opa-exports
          path: exports
